### PR TITLE
Fix/issue#7/for production

### LINKED ISSUE #7: Assignment_2.1
1. Create an issue for the current assignment and fill it out as discussed in the previous module on GIT practices.

2. Create a branch off of the tag v0.2 for the changes requested in this exercise and name it appropriately (again, as discussed in the previous module on GIT practices).

3. Try to apply as much of the principles discussed in the guidelines document and your own prior experience to reformat and refactor the provided script into a version that is production ready and create a PR.

4. The submitted version should have the following:

 - An updated README  document on how to install/run your code
 - An env.yaml which is the conda environment file that records all the required dependencies of your script. The README should talk about how to install your code and run it.
- Make your code packageable and installable as a library ([Here is a reference ](https://python-packaging-tutorial.readthedocs.io/en/latest/setup_py.html)to python packaging). Refer to the section on the recommended project layout.
- Basic tests (can be scripts) to verify correct installation. Again, refer to the section on project layout for where to place these tests.
- Create ML workflow scripts:
- A script (ingest_data.py)to download and create training and validation datasets. The script should accept the output folder/file path as an user argument.
- A script (train.py) to train the model(s). The script should accept arguments for input (dataset) and output folders (model pickles).
- A script (score.py) to score the model(s). The script should accept arguments for model folder, dataset folder and any outputs.
- NOTES:
- For the above scripts, use the argparse module to accept user arguments when running the scripts. Here is a [quick tutorial ](https://docs.python.org/3/howto/argparse.html)on how to use argparse.
- Ensure that your scripts generate a log for each script run ([Here is Tiger’s reference ](https://tigeranalytics-code-templates.readthedocs-hosted.com/en/latest/developer_guide/coding_best_practices.html#logging)with some example code on logging). Support accepting arguments (to your scripts) for the following
- specify the log level (e.g. `--log-level DEBUG`)
- use a log file or not (e.g. `--log-path <path>`, default case would be to not write logs to a file)
- toggle whether or not to write logs to the console (e.g. `--no-console-log`, default case would be to always write logs to console)
- When arguments are not specified, use the appropriate folders from the recommended project layout as the defaults (e.g. data, artifacts, logs etc.)
- Feel free to use a configuration file for the default arguments. But, the scripts should still override the config file values if explicitly passed by the user.

- Add unit tests and functional tests to your library ([Here is a short introduction ](https://tigeranalytics-code-templates.readthedocs-hosted.com/en/latest/developer_guide/coding_best_practices.html#code-testing)to testing principles and some example code).

- Setup a CI workflow using Github actions to build and test pull requests. Workflow can be defined by a YAML file checked into your github repository and should run when triggered by an event in your repository such as when the PR is raised. You can use earlier written unit tests and style tests as testing scripts. Paste the test coverage report/screenshot as part of the PR description. 
- Refer https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python for information on setting it up for pytest and linting using flake8.

- Use Sphinx to generate HTML documents for your library ([Here is a short write up ](https://tigeranalytics-code-templates.readthedocs-hosted.com/en/latest/developer_guide/coding_best_practices.html#documentation)on Sphinx and an example). Note that, at Tiger, we use the [Numpy docstring style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). Pls. ensure the docstrings follow the same style.

### PR DESCRIPTION
**Pull request by genuinesaravanan**
The following things are updated in this PR

1.  Readme file
2. conda environmental file
3. ML workflow (data_ingest.py, train.py and score.py)
4. logging
5. github action setup

This will close #7 

The screenshot of git hub actions output

image

### CODE REVIEW

**Review by sarath-srinivas — CHANGES_REQUESTED** [review]
Good job!. Few suggestions:
1. The `src` layout for python package is `src/<pkg-name>/__init__.py`. i.e, the package lives under the `src` directory as a folder which contains `__init__.py` besides other module files.
2. In the docstrings `Returns` should be used in place of `yields`. `yields` is meant for generators. https://numpydoc.readthedocs.io/en/latest/format.html#returns
3. The test files are empty. Maybe you already merged them?

**Comment by genuinesaravanan** [comment]
Thanks for the suggestions. I will do the necessary changes.
I will check for the test files

**Comment by genuinesaravanan** [comment]
Sarath, I have made the changes you have suggested. unfortunately I have modified the existing files for the assignment 3 before doing those changes. 
I merge this pull request for now and the changes will be reflected in the next pull request (assignment 3). 

I will make sure that this wont happen in future

**Comment by sarath-srinivas** [comment]
No problem

**Pull request merged**
